noinst_PROGRAMS =
noinst_PROGRAMS += test-mongo-bson
noinst_PROGRAMS += test-mongo-client
noinst_PROGRAMS += test-mongo-collection
noinst_PROGRAMS += test-mongo-cursor
noinst_PROGRAMS += test-mongo-object-id

TEST_PROGS += test-mongo-bson
TEST_PROGS += test-mongo-client
TEST_PROGS += test-mongo-collection
TEST_PROGS += test-mongo-cursor
TEST_PROGS += test-mongo-object-id

test_mongo_bson_SOURCES = $(top_srcdir)/tests/test-mongo-bson.c
test_mongo_bson_CPPFLAGS = $(GIO_CFLAGS) $(GOBJECT_CFLAGS) '-DSRC_DIR="$(top_srcdir)"'
test_mongo_bson_LDADD = $(GIO_LIBS) $(GOBJECT_LIBS) $(top_builddir)/libmongo-glib-1.0.la

test_mongo_client_SOURCES = $(top_srcdir)/tests/test-mongo-client.c
test_mongo_client_CPPFLAGS = $(GIO_CFLAGS) $(GOBJECT_CFLAGS)
test_mongo_client_LDADD = $(GIO_LIBS) $(GOBJECT_LIBS) $(top_builddir)/libmongo-glib-1.0.la

test_mongo_collection_SOURCES = $(top_srcdir)/tests/test-mongo-collection.c
test_mongo_collection_CPPFLAGS = $(GIO_CFLAGS) $(GOBJECT_CFLAGS)
test_mongo_collection_LDADD = $(GIO_LIBS) $(GOBJECT_LIBS) $(top_builddir)/libmongo-glib-1.0.la

test_mongo_cursor_SOURCES = $(top_srcdir)/tests/test-mongo-cursor.c
test_mongo_cursor_CPPFLAGS = $(GIO_CFLAGS) $(GOBJECT_CFLAGS)
test_mongo_cursor_LDADD = $(GIO_LIBS) $(GOBJECT_LIBS) $(top_builddir)/libmongo-glib-1.0.la

test_mongo_object_id_SOURCES = $(top_srcdir)/tests/test-mongo-object-id.c
test_mongo_object_id_CPPFLAGS = $(GIO_CFLAGS) $(GOBJECT_CFLAGS)
test_mongo_object_id_LDADD = $(GIO_LIBS) $(GOBJECT_LIBS) $(top_builddir)/libmongo-glib-1.0.la

EXTRA_DIST += $(top_srcdir)/tests/bson/*.bson
EXTRA_DIST += $(top_srcdir)/tests/test-helper.h
